/**
 * Generated by scripts/generate-country-lists.ts. Do not edit by hand.
 *
 *   pnpm exec tsx scripts/generate-country-lists.ts
 *
 * Source: data/country-guides.json, 6992 UKHSA migrant health rows
 * across 135 countries, Open Government Licence v3.0. Slugs resolve to
 * ISO 3166-1 alpha-2 through ICU's region names plus the alias table in the
 * script. Dropped slugs: none.
 *
 * A rule gates on a list here and cites the rows here. No recommendation text is
 * templated from one: the rows are clinician-facing prose that names no
 * destination, no specimen and no interval, and a recommendation whose text came
 * out of a row is generated. See docs/adr/0015-country-guides-gate-and-cite.md.
 *
 * Nothing here is dated, so a re-run on unchanged guidance is a no-op diff and
 * any real diff is UKHSA having revised a guide.
 */
import type { Citation } from './types'

/**
 * Every country the guides cover.
 *
 * Query: distinct countrySlug, every row
 * Matched: 135 countries.
 *
 * Not a rule gate. `ukhsa-new-arrival-orientation` declares `countries: 'all'`
 * so that it fires for a patient from a country with no guide at all; this list
 * is what the tests iterate to show it fires for every country that has one.
 * All 135 of them cite the NHS entitlements guide, which is why that rule
 * is available to anyone.
 */
export const GUIDE_COUNTRIES: string[] = [
  "AE", "AF", "AG", "AL", "AM", "AO", "AR", "AZ", "BA", "BB", "BD", "BG",
  "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BW", "BY", "BZ", "CD", "CF",
  "CG", "CI", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CZ", "DJ", "DM",
  "DO", "DZ", "EC", "EE", "EG", "ER", "ET", "FJ", "GD", "GE", "GH", "GM",
  "GN", "GT", "GW", "GY", "HN", "HR", "HU", "ID", "IL", "IN", "IQ", "IR",
  "JM", "JO", "JP", "KE", "KH", "KN", "KR", "KW", "KZ", "LA", "LB", "LC",
  "LK", "LR", "LS", "LT", "LV", "LY", "MA", "MD", "MG", "MM", "MN", "MU",
  "MW", "MX", "MY", "MZ", "NA", "NG", "NI", "NP", "OM", "PA", "PE", "PG",
  "PH", "PK", "PL", "PY", "QA", "RO", "RU", "RW", "SA", "SB", "SC", "SD",
  "SG", "SI", "SK", "SL", "SN", "SO", "SR", "SV", "SY", "SZ", "TG", "TH",
  "TN", "TR", "TT", "TZ", "UA", "UG", "UY", "UZ", "VC", "VE", "VN", "YE",
  "ZA", "ZM", "ZW",
]

/**
 * Countries whose UKHSA guide recommends hepatitis B screening for new arrivals.
 *
 * Query: distinct countrySlug where section ~ /hepatitis b/i and text ~ /consider screening for hepatitis B/i
 * Matched: 98 of 135 countries.
 *
 * The remaining 37 carry a hepatitis B section without that line, almost
 * all of them stating low prevalence, so the gate is the guidance's own and not
 * a threshold we chose.
 */
export const HEPB_SCREENING_COUNTRIES: string[] = [
  "AF", "AG", "AL", "AM", "AO", "AZ", "BD", "BG", "BH", "BI", "BJ", "BN",
  "BW", "BY", "CD", "CF", "CG", "CI", "CM", "CN", "CO", "CV", "CZ", "DJ",
  "DO", "DZ", "EE", "EG", "ER", "ET", "FJ", "GE", "GH", "GM", "GN", "GW",
  "GY", "HU", "IN", "IQ", "JM", "JO", "KE", "KH", "KR", "KZ", "LA", "LK",
  "LR", "LS", "LT", "LV", "LY", "MD", "MG", "MM", "MN", "MU", "MW", "MY",
  "MZ", "NA", "NG", "NP", "OM", "PE", "PG", "PH", "PK", "PL", "RO", "RU",
  "RW", "SA", "SB", "SC", "SD", "SG", "SL", "SN", "SO", "SR", "SY", "SZ",
  "TG", "TH", "TN", "TR", "TT", "TZ", "UG", "UY", "UZ", "VN", "YE", "ZA",
  "ZM", "ZW",
]

/**
 * The rows a hepatitis B recommendation attaches as secondary citations: the
 * screening line the gate matched, and the prevalence statement it hangs off,
 * which is the part that names the country. Both from the patient's own guide
 * page. See ADR 15.
 *
 * Query: rows where section ~ /hepatitis b/i and text ~ /consider screening for hepatitis B/i
 *        or where section ~ /hepatitis b/i and text ~ /(high|intermediate) prevalence of (of )?hepatitis B/i
 *
 * Quotes are verbatim from data/country-guides.json. Keyed by the same codes as
 * HEPB_SCREENING_COUNTRIES, so the gate and the citation cannot disagree.
 */
export const HEPB_GUIDE_ROWS: Record<string, [Citation, ...Citation[]]> = {
  AF: [
    { url: "https://www.gov.uk/guidance/afghanistan-migrant-health-guide", quote: "Afghanistan has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/afghanistan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  AG: [
    { url: "https://www.gov.uk/guidance/antigua-and-barbuda-migrant-health-guide", quote: "Antigua and Barbuda has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/antigua-and-barbuda-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  AL: [
    { url: "https://www.gov.uk/guidance/albania-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/albania-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  AM: [
    { url: "https://www.gov.uk/guidance/armenia-migrant-health-guide", quote: "Armenia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/armenia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  AO: [
    { url: "https://www.gov.uk/guidance/angola-migrant-health-guide", quote: "There is a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/angola-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  AZ: [
    { url: "https://www.gov.uk/guidance/azerbaijan-migrant-health-guide", quote: "Azerbaijan has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/azerbaijan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BD: [
    { url: "https://www.gov.uk/guidance/bangladesh-migrant-health-guide", quote: "Bangladesh has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/bangladesh-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BG: [
    { url: "https://www.gov.uk/guidance/bulgaria-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/bulgaria-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BH: [
    { url: "https://www.gov.uk/guidance/bahrain-migrant-health-guide", quote: "Bahrain has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/bahrain-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BI: [
    { url: "https://www.gov.uk/guidance/burundi-migrant-health-guide", quote: "Burundi has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/burundi-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BJ: [
    { url: "https://www.gov.uk/guidance/benin-migrant-health-guide", quote: "Benin has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/benin-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BN: [
    { url: "https://www.gov.uk/guidance/brunei-darussalam-migrant-health-guide", quote: "Brunei Darussalam has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/brunei-darussalam-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BW: [
    { url: "https://www.gov.uk/guidance/botswana-migrant-health-guide", quote: "Botswana has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/botswana-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  BY: [
    { url: "https://www.gov.uk/guidance/belarus-migrant-health-guide", quote: "Belarus has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/belarus-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CD: [
    { url: "https://www.gov.uk/guidance/democratic-republic-of-congo-migrant-health-guide", quote: "Democratic Republic of Congo has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/democratic-republic-of-congo-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CF: [
    { url: "https://www.gov.uk/guidance/central-african-republic-migrant-health-guide", quote: "Central African Republic has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/central-african-republic-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CG: [
    { url: "https://www.gov.uk/guidance/congo-migrant-health-guide", quote: "Congo has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/congo-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CI: [
    { url: "https://www.gov.uk/guidance/cote-divoire-ivory-coast-migrant-health-guide", quote: "Côte d’Ivoire has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/cote-divoire-ivory-coast-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CM: [
    { url: "https://www.gov.uk/guidance/cameroon-migrant-health-guide", quote: "Cameroon has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/cameroon-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CN: [
    { url: "https://www.gov.uk/guidance/china-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/china-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CO: [
    { url: "https://www.gov.uk/guidance/colombia-migrant-health-guide", quote: "Colombia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/colombia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CV: [
    { url: "https://www.gov.uk/guidance/cape-verde-migrant-health-guide", quote: "Cape Verde has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/cape-verde-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  CZ: [
    { url: "https://www.gov.uk/guidance/czech-republic-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  DJ: [
    { url: "https://www.gov.uk/guidance/djibouti-migrant-health-guide", quote: "Djibouti has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/djibouti-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  DO: [
    { url: "https://www.gov.uk/guidance/dominican-republic-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/dominican-republic-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  DZ: [
    { url: "https://www.gov.uk/guidance/algeria-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/algeria-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  EE: [
    { url: "https://www.gov.uk/guidance/estonia-migrant-health-guide", quote: "Estonia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/estonia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  EG: [
    { url: "https://www.gov.uk/guidance/egypt-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  ER: [
    { url: "https://www.gov.uk/guidance/eritrea-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/eritrea-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  ET: [
    { url: "https://www.gov.uk/guidance/ethiopia-migrant-health-guide", quote: "Ethiopia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/ethiopia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  FJ: [
    { url: "https://www.gov.uk/guidance/fiji-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/fiji-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GE: [
    { url: "https://www.gov.uk/guidance/georgia-migrant-health-guide", quote: "Georgia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/georgia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GH: [
    { url: "https://www.gov.uk/guidance/ghana-migrant-health-guide", quote: "Ghana has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/ghana-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GM: [
    { url: "https://www.gov.uk/guidance/gambia-the-migrant-health-guide", quote: "The Gambia has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/gambia-the-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GN: [
    { url: "https://www.gov.uk/guidance/guinea-migrant-health-guide", quote: "Guinea has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/guinea-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GW: [
    { url: "https://www.gov.uk/guidance/guinea-bissau-migrant-health-guide", quote: "Guinea-Bissau has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/guinea-bissau-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  GY: [
    { url: "https://www.gov.uk/guidance/guyana-migrant-health-guide", quote: "Guyana has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/guyana-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  HU: [
    { url: "https://www.gov.uk/guidance/hungary-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  IN: [
    { url: "https://www.gov.uk/guidance/india-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/india-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  IQ: [
    { url: "https://www.gov.uk/guidance/iraq-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  JM: [
    { url: "https://www.gov.uk/guidance/jamaica-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/jamaica-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  JO: [
    { url: "https://www.gov.uk/guidance/jordan-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/jordan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  KE: [
    { url: "https://www.gov.uk/guidance/kenya-migrant-health-guide", quote: "Kenya has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/kenya-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  KH: [
    { url: "https://www.gov.uk/guidance/cambodia-migrant-health-guide", quote: "Cambodia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/cambodia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  KR: [
    { url: "https://www.gov.uk/guidance/south-korea-migrant-health-guide", quote: "South Korea has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/south-korea-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  KZ: [
    { url: "https://www.gov.uk/guidance/kazakhstan-migrant-health-guide", quote: "Kazakhstan has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/kazakhstan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LA: [
    { url: "https://www.gov.uk/guidance/laos-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/laos-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LK: [
    { url: "https://www.gov.uk/guidance/sri-lanka-migrant-health-guide", quote: "Sri Lanka has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/sri-lanka-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LR: [
    { url: "https://www.gov.uk/guidance/liberia-migrant-health-guide", quote: "Liberia has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/liberia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LS: [
    { url: "https://www.gov.uk/guidance/lesotho-migrant-health-guide", quote: "There is a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/lesotho-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LT: [
    { url: "https://www.gov.uk/guidance/lithuania-migrant-health-guide", quote: "Lithuania has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/lithuania-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LV: [
    { url: "https://www.gov.uk/guidance/latvia-migrant-health-guide", quote: "Latvia has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/latvia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  LY: [
    { url: "https://www.gov.uk/guidance/libya-migrant-health-guide", quote: "Libya has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/libya-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MD: [
    { url: "https://www.gov.uk/guidance/moldova-migrant-health-guide", quote: "Moldova has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/moldova-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MG: [
    { url: "https://www.gov.uk/guidance/madagascar-migrant-health-guide", quote: "Madagascar has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/madagascar-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MM: [
    { url: "https://www.gov.uk/guidance/myanmar-burma-migrant-health-guide", quote: "Myanmar has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/myanmar-burma-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MN: [
    { url: "https://www.gov.uk/guidance/mongolia-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/mongolia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MU: [
    { url: "https://www.gov.uk/guidance/mauritius-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/mauritius-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MW: [
    { url: "https://www.gov.uk/guidance/malawi-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/malawi-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MY: [
    { url: "https://www.gov.uk/guidance/malaysia-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/malaysia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  MZ: [
    { url: "https://www.gov.uk/guidance/mozambique-migrant-health-guide", quote: "Mozambique has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/mozambique-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  NA: [
    { url: "https://www.gov.uk/guidance/namibia-migrant-health-guide", quote: "Namibia has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/namibia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  NG: [
    { url: "https://www.gov.uk/guidance/nigeria-migrant-health-guide", quote: "Nigeria has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/nigeria-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  NP: [
    { url: "https://www.gov.uk/guidance/nepal-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  OM: [
    { url: "https://www.gov.uk/guidance/oman-migrant-health-guide", quote: "Oman has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/oman-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  PE: [
    { url: "https://www.gov.uk/guidance/peru-migrant-health-guide", quote: "Peru has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/peru-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  PG: [
    { url: "https://www.gov.uk/guidance/papua-new-guinea-migrant-health-guide", quote: "Papua New Guinea has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/papua-new-guinea-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  PH: [
    { url: "https://www.gov.uk/guidance/philippines-migrant-health-guide", quote: "The Philippines has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/philippines-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  PK: [
    { url: "https://www.gov.uk/guidance/pakistan-migrant-health-guide", quote: "Pakistan has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/pakistan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  PL: [
    { url: "https://www.gov.uk/guidance/poland-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  RO: [
    { url: "https://www.gov.uk/guidance/romania-migrant-health-guide", quote: "Romania has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/romania-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  RU: [
    { url: "https://www.gov.uk/guidance/russia-migrant-health-guide", quote: "Russia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/russia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  RW: [
    { url: "https://www.gov.uk/guidance/rwanda-migrant-health-guide", quote: "Rwanda has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/rwanda-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SA: [
    { url: "https://www.gov.uk/guidance/saudi-arabia-migrant-health-guide", quote: "Saudi Arabia has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/saudi-arabia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SB: [
    { url: "https://www.gov.uk/guidance/solomon-islands-migrant-health-guide", quote: "There is a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/solomon-islands-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SC: [
    { url: "https://www.gov.uk/guidance/seychelles-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/seychelles-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SD: [
    { url: "https://www.gov.uk/guidance/sudan-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/sudan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SG: [
    { url: "https://www.gov.uk/guidance/singapore-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/singapore-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SL: [
    { url: "https://www.gov.uk/guidance/sierra-leone-migrant-health-guide", quote: "Sierra Leone has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/sierra-leone-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SN: [
    { url: "https://www.gov.uk/guidance/senegal-migrant-health-guide", quote: "There is a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/senegal-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SO: [
    { url: "https://www.gov.uk/guidance/somalia-migrant-health-guide", quote: "Somalia has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/somalia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SR: [
    { url: "https://www.gov.uk/guidance/suriname-migrant-health-guide", quote: "Suriname has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/suriname-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SY: [
    { url: "https://www.gov.uk/guidance/syria-migrant-health-guide", quote: "Syria has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/syria-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  SZ: [
    { url: "https://www.gov.uk/guidance/swaziland-migrant-health-guide", quote: "Swaziland has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/swaziland-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  TG: [
    { url: "https://www.gov.uk/guidance/togo-migrant-health-guide", quote: "Togo has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/togo-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  TH: [
    { url: "https://www.gov.uk/guidance/thailand-migrant-health-guide", quote: "Thailand has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/thailand-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  TN: [
    { url: "https://www.gov.uk/guidance/tunisia-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/tunisia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly for those who have recently arrived" },
  ],
  TR: [
    { url: "https://www.gov.uk/guidance/turkey-migrant-health-guide", quote: "Turkey has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/turkey-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  TT: [
    { url: "https://www.gov.uk/guidance/trinidad-and-tobago-migrant-health-guide", quote: "Trinidad and Tobago has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/trinidad-and-tobago-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  TZ: [
    { url: "https://www.gov.uk/guidance/tanzania-migrant-health-guide", quote: "Tanzania has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/tanzania-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  UG: [
    { url: "https://www.gov.uk/guidance/uganda-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/uganda-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  UY: [
    { url: "https://www.gov.uk/guidance/uruguay-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/uruguay-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  UZ: [
    { url: "https://www.gov.uk/guidance/uzbekistan-migrant-health-guide", quote: "Uzbekistan has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/uzbekistan-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  VN: [
    { url: "https://www.gov.uk/guidance/vietnam-migrant-health-guide", quote: "Vietnam has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/vietnam-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  YE: [
    { url: "https://www.gov.uk/guidance/yemen-migrant-health-guide", quote: "Yemen has a high prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/yemen-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  ZA: [
    { url: "https://www.gov.uk/guidance/south-africa-migrant-health-guide", quote: "South Africa has an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/south-africa-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  ZM: [
    { url: "https://www.gov.uk/guidance/zambia-migrant-health-guide", quote: "There is an intermediate prevalence of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/zambia-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
  ZW: [
    { url: "https://www.gov.uk/guidance/zimbabwe-migrant-health-guide", quote: "Zimbabwe has an intermediate prevalence of of hepatitis B , so:" },
    { url: "https://www.gov.uk/guidance/zimbabwe-migrant-health-guide", quote: "consider screening for hepatitis B, particularly those who have recently arrived" },
  ],
}
